-- Supabase feature schema for Scan/Community flow
-- Scope:
-- 1) scan history (private)
-- 2) confirmed purchases
-- 3) auto-generated community posts
-- 4) products / markets master
-- 5) exchange rate snapshot
--
-- Note: this migration is safe to review locally first.

begin;

create extension if not exists pgcrypto;
create extension if not exists citext;

-- Product master
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  code text unique, -- e.g. p001
  name text not null,
  default_unit text not null default 'kg',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Market / store master used by map + community filters.
create table if not exists public.markets (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique,
  company_name text,
  country_code text not null default 'EG',
  city text,
  district text,
  lat double precision,
  lng double precision,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Captured image history for each user (app-private history).
create table if not exists public.scan_histories (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid references auth.users(id) on delete cascade,
  client_user_id text not null, -- app-side UUID fallback when auth not wired yet
  image_path text not null, -- storage path, not raw bytes
  created_at timestamptz not null default now()
);

-- Confirmed purchases at scan flow.
create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid references auth.users(id) on delete set null,
  client_user_id text not null,
  product_id uuid not null references public.products(id),
  market_id uuid references public.markets(id),
  product_name_override text,
  store_name_override text,
  location_override text,
  unit text not null default 'kg',
  quantity numeric(10,2) not null default 1,
  final_price_egp numeric(12,2) not null check (final_price_egp >= 0),
  detected_price_egp numeric(12,2) check (detected_price_egp is null or detected_price_egp >= 0),
  image_path text,
  created_at timestamptz not null default now()
);

-- Public community feed rows.
-- One purchase -> one community post (auto generated by trigger).
create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null unique references public.purchases(id) on delete cascade,
  auth_user_id uuid references auth.users(id) on delete set null,
  client_user_id text not null,
  product_id uuid not null references public.products(id),
  market_id uuid references public.markets(id),
  product_name_cache text not null,
  store_name_cache text not null,
  location_cache text not null,
  price_egp numeric(12,2) not null check (price_egp >= 0),
  image_path text,
  created_at timestamptz not null default now()
);

-- Exchange-rate snapshot (fetch once at app launch, then cache).
create table if not exists public.exchange_rates (
  id bigserial primary key,
  base_currency text not null,
  quote_currency text not null,
  rate numeric(18,6) not null check (rate > 0),
  as_of_date date not null,
  source text,
  created_at timestamptz not null default now(),
  unique (base_currency, quote_currency, as_of_date)
);

insert into storage.buckets (id, name, public)
values ('community-images', 'community-images', true)
on conflict (id) do nothing;

create index if not exists idx_products_code on public.products(code);
create index if not exists idx_markets_name on public.markets(name);
create index if not exists idx_scan_histories_client_created_at
  on public.scan_histories(client_user_id, created_at desc);
create index if not exists idx_purchases_product_created_at
  on public.purchases(product_id, created_at desc);
create index if not exists idx_purchases_client_created_at
  on public.purchases(client_user_id, created_at desc);
create index if not exists idx_community_posts_created_at
  on public.community_posts(created_at desc);
create index if not exists idx_community_posts_product_cache
  on public.community_posts(lower(product_name_cache));
create index if not exists idx_community_posts_store_cache
  on public.community_posts(lower(store_name_cache));
create index if not exists idx_community_posts_location_cache
  on public.community_posts(lower(location_cache));
create index if not exists idx_exchange_rates_pair_date
  on public.exchange_rates(base_currency, quote_currency, as_of_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_products_set_updated_at on public.products;
create trigger trg_products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_markets_set_updated_at on public.markets;
create trigger trg_markets_set_updated_at
before update on public.markets
for each row execute function public.set_updated_at();

create or replace function public.sync_community_post_from_purchase()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_name text;
  v_store_name text;
  v_location text;
begin
  select p.name into v_product_name
  from public.products p
  where p.id = new.product_id;

  select
    coalesce(m.name, 'Traveler Report'),
    coalesce(m.district, m.city, 'Unknown')
  into v_store_name, v_location
  from public.markets m
  where m.id = new.market_id;

  insert into public.community_posts (
    purchase_id,
    auth_user_id,
    client_user_id,
    product_id,
    market_id,
    product_name_cache,
    store_name_cache,
    location_cache,
    price_egp,
    image_path,
    created_at
  ) values (
    new.id,
    new.auth_user_id,
    new.client_user_id,
    new.product_id,
    new.market_id,
    coalesce(new.product_name_override, v_product_name, 'Unknown Product'),
    coalesce(new.store_name_override, v_store_name, 'Traveler Report'),
    coalesce(new.location_override, v_location, 'Unknown'),
    new.final_price_egp,
    new.image_path,
    new.created_at
  )
  on conflict (purchase_id) do update
  set
    auth_user_id = excluded.auth_user_id,
    client_user_id = excluded.client_user_id,
    product_id = excluded.product_id,
    market_id = excluded.market_id,
    product_name_cache = excluded.product_name_cache,
    store_name_cache = excluded.store_name_cache,
    location_cache = excluded.location_cache,
    price_egp = excluded.price_egp,
    image_path = excluded.image_path;

  return new;
end;
$$;

drop trigger if exists trg_purchases_sync_community_post on public.purchases;
create trigger trg_purchases_sync_community_post
after insert on public.purchases
for each row execute function public.sync_community_post_from_purchase();

-- RLS
alter table public.scan_histories enable row level security;
alter table public.purchases enable row level security;
alter table public.community_posts enable row level security;
alter table public.exchange_rates enable row level security;

drop policy if exists scan_histories_select_owner on public.scan_histories;
create policy scan_histories_select_owner on public.scan_histories
for select
using (auth.uid() = auth_user_id);

drop policy if exists scan_histories_insert_owner on public.scan_histories;
create policy scan_histories_insert_owner on public.scan_histories
for insert
with check (auth.uid() = auth_user_id);

drop policy if exists scan_histories_delete_owner on public.scan_histories;
create policy scan_histories_delete_owner on public.scan_histories
for delete
using (auth.uid() = auth_user_id);

drop policy if exists purchases_select_owner on public.purchases;
create policy purchases_select_owner on public.purchases
for select
using (auth.uid() = auth_user_id);

drop policy if exists purchases_insert_owner on public.purchases;
create policy purchases_insert_owner on public.purchases
for insert
with check (auth.uid() = auth_user_id);

drop policy if exists purchases_insert_anon_mvp on public.purchases;
create policy purchases_insert_anon_mvp on public.purchases
for insert
to anon
with check (auth_user_id is null and length(client_user_id) > 0);

drop policy if exists purchases_update_owner on public.purchases;
create policy purchases_update_owner on public.purchases
for update
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists community_posts_select_all on public.community_posts;
create policy community_posts_select_all on public.community_posts
for select
using (true);

drop policy if exists community_posts_update_owner on public.community_posts;
create policy community_posts_update_owner on public.community_posts
for update
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists community_posts_delete_owner on public.community_posts;
create policy community_posts_delete_owner on public.community_posts
for delete
using (auth.uid() = auth_user_id);

drop policy if exists exchange_rates_select_all on public.exchange_rates;
create policy exchange_rates_select_all on public.exchange_rates
for select
using (true);

drop policy if exists storage_community_images_read_all on storage.objects;
create policy storage_community_images_read_all on storage.objects
for select
to public
using (bucket_id = 'community-images');

drop policy if exists storage_community_images_insert_all on storage.objects;
create policy storage_community_images_insert_all on storage.objects
for insert
to public
with check (bucket_id = 'community-images');

drop policy if exists storage_community_images_update_all on storage.objects;
create policy storage_community_images_update_all on storage.objects
for update
to public
using (bucket_id = 'community-images')
with check (bucket_id = 'community-images');

-- If you plan to query exchange rates from mobile directly, keep only SELECT policy.
-- Upsert should be done by Edge Function or backend service role.

commit;
