from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".env"
TARGET = (
    ROOT
    / "frontend"
    / "flutter_app"
    / "lib"
    / "core"
    / "constants"
    / "generated_env.dart"
)
WEB_MAPS_CONFIG_TARGET = ROOT / "frontend" / "flutter_app" / "web" / "maps_config.js"
IOS_MAPS_SECRETS = (
    ROOT
    / "frontend"
    / "flutter_app"
    / "ios"
    / "Flutter"
    / "MapsSecrets.xcconfig"
)
CLIENT_KEYS = {
    "TRUEPRICE_API_BASE_URL",
    "TRUEPRICE_EXCHANGE_RATE_API_URL",
}
WEB_MAPS_KEY = "GOOGLE_MAPS_WEB_API_KEY"
IOS_MAPS_KEY = "GMS_API_KEY"


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing env file: {SOURCE}")

    data = _read_dotenv(SOURCE)
    client_data = {key: data[key] for key in CLIENT_KEYS if data.get(key)}
    missing_keys = sorted(CLIENT_KEYS - client_data.keys())
    if missing_keys:
        raise SystemExit(f"Missing {', '.join(missing_keys)} in .env")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(_render_dart_env(client_data), encoding="utf-8")
    print(f"Wrote Flutter env constants: {TARGET}")

    maps_key = data.get(WEB_MAPS_KEY) or _read_optional_key(
        IOS_MAPS_SECRETS,
        IOS_MAPS_KEY,
    )
    WEB_MAPS_CONFIG_TARGET.write_text(
        _render_web_maps_config(maps_key),
        encoding="utf-8",
    )
    print(f"Wrote web maps config: {WEB_MAPS_CONFIG_TARGET}")


def _read_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def _render_dart_env(values: dict[str, str]) -> str:
    api_base_url = _dart_string(values["TRUEPRICE_API_BASE_URL"])
    exchange_rate_api_url = _dart_string(values["TRUEPRICE_EXCHANGE_RATE_API_URL"])
    return f"""// Generated by scripts/generate_flutter_defines.py. Do not edit.

class GeneratedEnv {{
  static const String truepriceApiBaseUrl = {api_base_url};
  static const String truepriceExchangeRateApiUrl = {exchange_rate_api_url};
}}
"""


def _read_optional_key(path: Path, key: str) -> str:
    if not path.exists():
        return ""
    return _read_dotenv(path).get(key, "")


def _render_web_maps_config(api_key: str) -> str:
    return (
        "// Generated by scripts/generate_flutter_defines.py. Do not edit.\n"
        f"window.TRUEPRICE_GOOGLE_MAPS_WEB_API_KEY = {_js_string(api_key)};\n"
    )


def _dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _js_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


if __name__ == "__main__":
    main()
