from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".env"
TARGET = (
    ROOT
    / "frontend"
    / "flutter_app"
    / "lib"
    / "core"
    / "constants"
    / "generated_env.dart"
)
CLIENT_KEYS = {"TRUEPRICE_API_BASE_URL"}


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing env file: {SOURCE}")

    data = _read_dotenv(SOURCE)
    client_data = {key: data[key] for key in CLIENT_KEYS if data.get(key)}
    if "TRUEPRICE_API_BASE_URL" not in client_data:
        raise SystemExit("Missing TRUEPRICE_API_BASE_URL in .env")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(_render_dart_env(client_data), encoding="utf-8")
    print(f"Wrote Flutter env constants: {TARGET}")


def _read_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def _render_dart_env(values: dict[str, str]) -> str:
    api_base_url = _dart_string(values["TRUEPRICE_API_BASE_URL"])
    return f"""// Generated by scripts/generate_flutter_defines.py. Do not edit.

class GeneratedEnv {{
  static const String truepriceApiBaseUrl = {api_base_url};
}}
"""


def _dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


if __name__ == "__main__":
    main()
